const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const events={},windowEvents={},elements=new Map();let authenticated=true,calls=[],hooks;
const task={ID:'TASK-TEST',Tarea:'Original',Estado:'Pendiente',_version:'version-original','Última edición por':null};
const snapshot={mode:'live',taskEditing:true,taskOptions:{Estado:['Pendiente','Completado']},tasks:[task],archivedTasks:[],projects:[],people:[],incoming:[],history:[],recommendations:[],criteria:[],ideas:[],dates:[],summary:[],modules:[]};
function el(id){if(!elements.has(id))elements.set(id,{id,innerHTML:'',value:'',textContent:'',open:false,dataset:{},addEventListener(){},focus(){},showModal(){this.open=true;},close(){this.open=false;},querySelectorAll(){return[];}});return elements.get(id);}
const field={dataset:{field:'Tarea'},value:'Edited task',type:'text',disabled:false};el('task-edit-form').querySelectorAll=()=>[field];
let fail=true;
const backend={configured:true,ready:()=>authenticated,call:async(method,p)=>{if(method==='getHubData')return snapshot;calls.push(p);if(fail){fail=false;authenticated=false;windowEvents['arc-auth-changed']();throw Error('Session expired');}task.Tarea=p.fields.Tarea;return {id:task.ID,verified:true};}};
const runtime={document:{getElementById:el,querySelectorAll:()=>[],addEventListener:(t,f)=>events[t]=f,activeElement:null},window:{ARC_BACKEND:backend,addEventListener:(t,f)=>windowEvents[t]=f,scrollTo(){},confirm:()=>true,__ARC_TEST_HOOK__:h=>hooks=h,crypto:{randomUUID:()=> 'request-task-ui-test'}},crypto:{randomUUID:()=> 'request-task-ui-test'},localStorage:{getItem:()=>null,setItem(){}},Intl,Date,URL,JSON,console,setInterval(){},setTimeout(){},clearTimeout(){}};
vm.createContext(runtime);vm.runInContext(fs.readFileSync(__dirname+'/../dist/app.js','utf8'),runtime);
const tick=()=>new Promise(r=>setImmediate(r));const click=(dataset,id)=>events.click({target:{closest:()=>({id,dataset,hasAttribute:()=>false})}});
(async()=>{await tick();await click({detail:'tasks|TASK-TEST'});await click({},'edit-task');events.input({target:{id:'task-field-0',closest:()=>true}});events.submit({target:{id:'task-edit-form'},preventDefault(){}});await tick();assert.equal(authenticated,false);assert.ok(!el('main').innerHTML.includes('Edited task'));assert.equal(el('detail-dialog').open,false);
 authenticated=true;windowEvents['arc-auth-changed']();await tick();await tick();assert.ok(el('main').innerHTML.includes('Recuperar edición'));await click({},'recover-task-draft');assert.equal(field.value,'Edited task');assert.equal(el('detail-dialog').open,true);events.submit({target:{id:'task-edit-form'},preventDefault(){}});await tick();await tick();assert.equal(task.Tarea,'Edited task');assert.equal(calls.length,2);assert.equal(calls[0].requestId,calls[1].requestId);assert.equal(calls[1].expectedVersion,'version-original');assert.equal(el('detail-dialog').open,false);assert.ok(!el('main').innerHTML.includes('Recuperar edición'));console.log('PASS: session loss hides private data, preserves task edits only in memory and recovers the same idempotent request after reconnect.');})().catch(e=>{console.error(e);process.exit(1)});
