const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const root=__dirname+'/..',schema=JSON.parse(fs.readFileSync(root+'/tests/fixtures/schema5.json','utf8'));
const extra=['Orden manual','Última edición por','Revisado por','Fecha revisión','Huella revisada','Feedback revisión'];
const original=JSON.parse(schema.find(r=>r[0]==='schema_columns:Tareas activas')[1]),activeHeaders=[...original,...extra],archiveHeaders=[...original,'Fecha cierre','Cierre / resultado',...extra];
const auditHeaders=['Request ID','Entidad ID','Fecha','Autor','Acción','Solicitud','Antes','Después'];
const values={};for(const [k,v]of schema)if(k.startsWith('schema_columns:'))values[k.slice(15)]=[JSON.parse(v)];
values.Sistema=[['Clave','Valor','Notas'],...schema.filter(r=>!['schema_version','schema_columns:Tareas activas','schema_columns:Tareas archivadas'].includes(r[0])),['schema_version','6'],['schema_columns:Tareas activas',JSON.stringify(activeHeaders)],['schema_columns:Tareas archivadas',JSON.stringify(archiveHeaders)],['source_tasks_archived','Tareas archivadas'],['source_catalogs','Catálogos'],['source_task_changes','Cambios HUB'],['task_edit_status','activo'],['schema_columns:Cambios HUB',JSON.stringify(auditHeaders)]];
values['Tareas activas']=[activeHeaders];values['Tareas archivadas']=[archiveHeaders];values['Cambios HUB']=[auditHeaders];
const core='synthetic-core',owner='owner@example.invalid';let active=owner,writes=0,locked=false,failArchive=0,formulaField=null;
values.Módulos=[values.Módulos[0],['MOD-CORE','General','Personal','Google Sheets',core,'https://example.invalid','Core','Activo',6,'Test']];
values.Proyectos.push(['P1','Test project']);
for(const state of ['Pendiente','En curso','En espera','Completado','Cancelado'])values.Catálogos.push(['Estado tarea',state,true]);
for(const [catalog,options]of Object.entries({'Prioridad tarea':['Alta','Media','Baja'],'Contexto ejecución':['Móvil','Ordenador','Presencial','Cualquier sitio'],Concentración:['Baja','Media','Alta']}))for(const v of options)values.Catálogos.push([catalog,v,true]);
function addTask(id,order){const t={ID:id,Tarea:'Task '+id,Estado:'Pendiente','Orden manual':order,'Fecha creación':46000,'Última actualización':46000,Delegable:false};values['Tareas activas'].push(activeHeaders.map(h=>t[h]??''));}
addTask('T1',1);addTask('T2',2);addTask('T3',3);
const ids=Object.fromEntries(Object.keys(values).map((n,i)=>[n,i+1]));
function sheet(n){return {getName:()=>n,getSheetId:()=>ids[n],getLastRow:()=>values[n].length,getRange:(r,c,h,w)=>({getValues:()=>Array.from({length:h},(_,i)=>Array.from({length:w},(_,j)=>values[n][r-1+i]?.[c-1+j]??''))})};}
const book={getSheetByName:n=>values[n]?sheet(n):null,getSpreadsheetTimeZone:()=> 'Europe/Madrid',getUrl:()=> 'https://example.invalid',getName:()=> 'Synthetic'};
const val=c=>c.userEnteredValue?.stringValue??c.userEnteredValue?.numberValue??c.userEnteredValue?.boolValue??'';
const server={console,Date,JSON,Object,Number,String,Math,Set,Session:{getActiveUser:()=>({getEmail:()=>active}),getEffectiveUser:()=>({getEmail:()=>owner})},PropertiesService:{getScriptProperties:()=>({getProperty:k=>k==='HUB_CORE_ID'?core:owner})},SpreadsheetApp:{openById:()=>book,flush(){}},Utilities:{DigestAlgorithm:{SHA_256:'sha256'},Charset:{UTF_8:'utf8'},computeDigest:(a,s)=>[...crypto.createHash('sha256').update(s).digest()],formatDate:()=> '2026-10-05T19:00:00'},LockService:{getScriptLock:()=>({tryLock(){if(locked)return false;locked=true;return true;},releaseLock(){locked=false;}})},Sheets:{Spreadsheets:{get(id,o){const match=o.ranges[0].match(/^'(.+)'!A(\d+):/),n=match[1].replace(/''/g,"'"),row=Number(match[2]);return {sheets:[{data:[{rowData:[{values:values[n][row-1].map((v,i)=>({...((n==='Tareas activas'&&formulaField===i)?{userEnteredValue:{formulaValue:'=1'}}:v===''?{}:{userEnteredValue:typeof v==='number'?{numberValue:v}:typeof v==='boolean'?{boolValue:v}:{stringValue:v}}),userEnteredFormat:{wrapStrategy:'WRAP'}}))}]}]}]};},batchUpdate({requests}){for(const r of requests){if(r.appendCells&&r.appendCells.sheetId===ids['Tareas archivadas']&&failArchive-->0)throw Error('Archive temporarily unavailable');}writes++;for(const r of requests){if(r.updateCells){const {sheetId,rowIndex,columnIndex}=r.updateCells.start,n=Object.keys(ids).find(n=>ids[n]===sheetId);values[n][rowIndex][columnIndex]=val(r.updateCells.rows[0].values[0]);}if(r.appendCells){const n=Object.keys(ids).find(n=>ids[n]===r.appendCells.sheetId);values[n].push(r.appendCells.rows[0].values.map(val));}if(r.deleteDimension){const {sheetId,startIndex,endIndex}=r.deleteDimension.range,n=Object.keys(ids).find(n=>ids[n]===sheetId);values[n].splice(startIndex,endIndex-startIndex);}}}}}};
vm.createContext(server);vm.runInContext(fs.readFileSync(root+'/google/Code.gs','utf8'),server);
if(fs.existsSync(root+'/google/TaskEdits.gs'))vm.runInContext(fs.readFileSync(root+'/google/TaskEdits.gs','utf8'),server);
const data=()=>server.getHubData(),find=id=>[...data().tasks,...data().archivedTasks].find(t=>t.ID===id);
const edit=(id,fields,key='request-'+crypto.randomUUID())=>({id,fields,requestId:key,expectedVersion:find(id)._version});
let p=edit('T1',{Tarea:'=literal title','Fecha objetivo':'2026-10-31',Delegable:true,'Proyecto ID':'P1','Contexto / notas':'New context'}),receipt=server.updateTask(p);
assert.ok(receipt.verified);let t=find('T1');assert.equal(t.Tarea,'=literal title');assert.equal(t.Delegable,true);assert.equal(t.Proyecto,'Test project');assert.equal(t['Fecha objetivo'],46326);assert.equal(t['Última edición por'],'Arc');assert.equal(t['Revisado por'],null);assert.equal(values['Cambios HUB'].length,2);
const written=writes;server.updateTask(p);assert.equal(writes,written);assert.throws(()=>server.updateTask({...p,fields:{Tarea:'different'}}),/otro contenido/);
const stale=edit('T1',{Tarea:'Stale overwrite'});values['Tareas activas'][1][activeHeaders.indexOf('Contexto / notas')]='External correction';assert.throws(()=>server.updateTask(stale),/cambió/);assert.equal(find('T1').Tarea,'=literal title');
assert.throws(()=>server.updateTask(edit('T1',{ID:'new'})),/No se puede/);assert.throws(()=>server.updateTask(edit('T1',{'Fecha objetivo':'2026-02-30'})),/no existe/);assert.throws(()=>server.updateTask(edit('T1',{Estado:'Delegada'})),/no permitido/);
formulaField=activeHeaders.indexOf('Contexto / notas');assert.throws(()=>server.updateTask(edit('T1',{'Contexto / notas':'flatten formula'})),/fórmula/);formulaField=null;
active='other@example.invalid';assert.throws(()=>server.updateTask(p),/Acceso privado/);active=owner;
const order={ids:['T3','T1','T2'],versions:Object.fromEntries(data().tasks.map(t=>[t.ID,t._version])),requestId:'request-order-test'};
server.reorderTasks(order);assert.deepEqual(['T3','T1','T2'].map(id=>find(id)['Orden manual']),[1,2,3]);const once=writes;server.reorderTasks(order);assert.equal(writes,once);assert.throws(()=>server.reorderTasks({...order,ids:['T1','T1','T3'],requestId:'request-order-bad'}),/lista/);
// Closure: failure after the atomic edit/receipt leaves the source intact; retry finishes once.
p=edit('T1',{Estado:'Completado','Fecha completada':'2026-10-04'});failArchive=1;assert.throws(()=>server.updateTask(p),/temporarily/);assert.ok(data().tasks.some(t=>t.ID==='T1'));receipt=server.updateTask(p);assert.ok(receipt.verified);assert.equal(data().tasks.some(t=>t.ID==='T1'),false);assert.equal(data().archivedTasks.filter(t=>t.ID==='T1').length,1);assert.equal(find('T1')['Fecha completada'],46299);assert.equal(find('T1')['Fecha cierre'],46299);assert.equal(find('T1')['Contexto / notas'],'External correction');
server.updateTask(edit('T1',{Estado:'Pendiente'}));assert.equal(data().archivedTasks.some(t=>t.ID==='T1'),false);assert.equal(find('T1')['Fecha completada'],null);assert.equal(data().tasks.filter(t=>t.ID==='T1').length,1);
// Review validity is tied to exact current content, not a permanently green label.
t=find('T1');const reviewed=t._reviewFingerprint,row=values['Tareas activas'].find(r=>r[0]==='T1');row[activeHeaders.indexOf('Revisado por')]='Sistema';row[activeHeaders.indexOf('Huella revisada')]=reviewed;assert.equal(find('T1')._reviewFingerprint,reviewed);server.updateTask(edit('T1',{Responsable:'Arc'}));assert.notEqual(find('T1')._reviewFingerprint,reviewed);assert.equal(find('T1')['Huella revisada'],reviewed);
const incomingHeaders=[...values.Incoming[0],...extra];values.Incoming=[incomingHeaders];
values.Sistema.find(r=>r[0]==='schema_columns:Incoming')[1]=JSON.stringify(incomingHeaders);values.Sistema.push(['incoming_order_status','activo']);
for(const [id,state,rank,text] of [['I1','Pendiente',1,'Original one'],['I2','Revisar',2,'Original two'],['I3','Procesado',3,'Processed untouched']]){const r={ID:id,Estado:state,'Orden manual':rank,'Texto original':text};values.Incoming.push(incomingHeaders.map(h=>r[h]??''));}
const incPayload=()=>({ids:['I2','I1'],versions:Object.fromEntries(data().incoming.map(r=>[r.ID,r._version])),requestId:'request-incoming-test'});
let ip=incPayload();server.reorderIncoming(ip);assert.deepEqual(data().incoming.map(r=>r['Orden manual']),[2,1]);assert.equal(data().incoming[0]['Texto original'],'Original one');assert.equal(values.Incoming[3][incomingHeaders.indexOf('Orden manual')],3);assert.equal(data().incoming[0]['Última edición por'],'Arc');
let incWrites=writes;server.reorderIncoming(ip);assert.equal(writes,incWrites);assert.throws(()=>server.reorderIncoming({...ip,ids:['I1','I1'],requestId:'request-incoming-duplicate'}),/cambió/);
const staleInc={...incPayload(),ids:['I1','I2'],requestId:'request-incoming-stale'};values.Incoming[1][incomingHeaders.indexOf('Texto original')]='Manual authoritative correction';assert.throws(()=>server.reorderIncoming(staleInc),/cambió/);
const changedList={...incPayload(),requestId:'request-incoming-list'};values.Incoming[2][incomingHeaders.indexOf('Estado')]='Procesado';assert.throws(()=>server.reorderIncoming(changedList),/cambió/);
active='other@example.invalid';assert.throws(()=>server.reorderIncoming(ip),/Acceso privado/);active=owner;
assert.equal(locked,false);console.log('PASS: task edits and Incoming ordering; owner gate, exact open list, content conflicts, atomic idempotent receipts, text/state preservation and processed records untouched. Synthetic runtime only.');
